import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import Script from "next/script";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const naverClientID = process.env.NEXT_PUBLIC_NAVER_CLIENT_ID || "";
	return (
		<html lang="en">
			<Head>
				<title>유나로드</title>
			</Head>
			<body>
				<div className="inner-layout">{children}</div>
			</body>
		</html>
	);
}
